### ISSUE TITLE
error

### ISSUE THREAD

**Issue by plopomi** [kmahyyg/mremoteng-decrypt#4]
User Input: EWNFV5uGcjUHF0uS17QTdT9kVqtKCPeoC0Nw5dmaPFjNQ2kt/zO5xDqE4HdVmHAowVRdC7emf7lWWA10dQKiw==
Use default password for cracking...
org.bouncycastle.crypto.InvalidCipherTextException: mac check in GCM failed
	at org.bouncycastle.crypto.modes.GCMBlockCipher.doFinal(Unknown Source)
	at xyz.kmahyyg.htb_mr3m.Main.decryptAEADgcm(Main.java:94)
	at xyz.kmahyyg.htb_mr3m.Main.main(Main.java:70)

 Error Occured While Trying to Decrypt the AES-128-GCM. 

can someone help me, please ?

**Comment by kmahyyg** [comment]
Could you please show me the full command you issue? And also which file is the string you input coming from?

**Comment by kmahyyg** [comment]
The python version written by another guy also showed that you offered us an invalid Base64 string, please check if you find the correct encrypted string.

```bash
$ python3 ./mremoteng_decrypt.py -s EWNFV5uGcjUHF0uS17QTdT9kVqtKCPeoC0Nw5dmaPFjNQ2kt/zO5xDqE4HdVmHAowVRdC7emf7lWWA10dQKiw==
Traceback (most recent call last):
  File "./mremoteng_decrypt.py", line 49, in <module>
    main()
  File "./mremoteng_decrypt.py", line 30, in main
    encrypted_data = base64.b64decode(encrypted_data)
  File "/usr/lib/python3.7/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (85) cannot be 1 more than a multiple of 4
```

**Comment by kmahyyg** [comment]
Due to no response, closed. Lack of information to debug.
